export const cars = [
  {
    id: "ferrari-roma-2023",
    slug: "ferrari-roma-2023",
    make: "Ferrari",
    model: "Roma",
    year: 2023,
    price: 298000,
    mileage: 1200,
    transmission: "8-Speed DCT",
    engine: "3.9L Twin-Turbo V8",
    horsepower: 612,
    torque: "561 lb-ft",
    zeroToSixty: "3.4s",
    topSpeed: "199 mph",
    exteriorColor: "Rosso Corsa",
    interiorColor: "Cuoio Leather",
    weight: "3,461 lbs",
    dimensions: "179.9\" L × 79.5\" W × 52.5\" H",
    cargo: "7.9 cu ft",
    description:
      "The Roma distills Ferrari's grand touring legacy into its purest modern form. A front-mid mounted twin-turbo V8, a 2+ seater fastback body, and a character that rewards restraint as much as aggression.",
    tagline: "La Nuova Dolce Vita.",
    featured: true,
    images: [
      "/cars/ferrari-roma-2023-1.jpg",
      "/cars/ferrari-roma-2023-2.jpg",
      "/cars/ferrari-roma-2023-3.jpg",
      "/cars/ferrari-roma-2023-4.jpg",
    ],
  },
  {
    id: "ferrari-sf90-stradale-2022",
    slug: "ferrari-sf90-stradale-2022",
    make: "Ferrari",
    model: "SF90 Stradale",
    year: 2022,
    price: 625000,
    mileage: 890,
    transmission: "8-Speed DCT",
    engine: "4.0L Twin-Turbo V8 + 3 Electric Motors",
    horsepower: 986,
    torque: "590 lb-ft",
    zeroToSixty: "2.5s",
    topSpeed: "211 mph",
    exteriorColor: "Giallo Modena",
    interiorColor: "Black Alcantara",
    weight: "3,461 lbs",
    dimensions: "178.2\" L × 78.0\" W × 47.4\" H",
    cargo: "5.3 cu ft",
    description:
      "Ferrari's most powerful series-production car ever built. Plug-in hybrid architecture, three electric motors, and a 4.0L twin-turbo V8 work in perfect concert to redefine what a supercar can be.",
    tagline: "The summit of the range.",
    featured: true,
    images: [
      "/cars/ferrari-sf90-stradale-2022-4.jpg",
      "/cars/ferrari-sf90-stradale-2022-2.jpg",
      "/cars/ferrari-sf90-stradale-2022-3.jpg",
      "/cars/ferrari-sf90-stradale-2022-1.jpg",
    ],
  },
  {
    id: "lamborghini-huracan-evo-2022",
    slug: "lamborghini-huracan-evo-2022",
    make: "Lamborghini",
    model: "Huracán EVO",
    year: 2022,
    price: 285000,
    mileage: 4200,
    transmission: "7-Speed DCT",
    engine: "5.2L V10 Naturally Aspirated",
    horsepower: 630,
    torque: "443 lb-ft",
    zeroToSixty: "2.9s",
    topSpeed: "202 mph",
    exteriorColor: "Arancio Borealis",
    interiorColor: "Black Alcantara",
    weight: "3,135 lbs",
    dimensions: "175.6\" L × 75.7\" W × 45.9\" H",
    cargo: "3.5 cu ft",
    description:
      "One of the last naturally aspirated V10 exotics on the market. The Huracán EVO screams to 8,000 RPM with a mechanical honesty that turbocharged rivals simply cannot match.",
    tagline: "Pure V10. No compromises.",
    featured: true,
    images: [
      "/cars/lamborghini-huracan-evo-2022-2.jpg",
      "/cars/lamborghini-huracan-evo-2022-1.jpg",
      "/cars/lamborghini-huracan-evo-2022-4.jpg",
      "/cars/lamborghini-huracan-evo-2022-3.jpg",
    ],
  },
  {
    id: "lamborghini-urus-s-2023",
    slug: "lamborghini-urus-s-2023",
    make: "Lamborghini",
    model: "Urus S",
    year: 2023,
    price: 248000,
    mileage: 3100,
    transmission: "8-Speed Automatic",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 657,
    torque: "627 lb-ft",
    zeroToSixty: "3.5s",
    topSpeed: "189 mph",
    exteriorColor: "Blu Eleos",
    interiorColor: "Cognac Leather",
    weight: "4,850 lbs",
    dimensions: "201.3\" L × 79.9\" W × 64.4\" H",
    cargo: "56.3 cu ft",
    description:
      "The world's fastest SUV, refined. The Urus S delivers supercar performance without conceding an inch of daily usability. Four adults, full luggage, and a sub-4-second sprint to sixty.",
    tagline: "The Super SUV, elevated.",
    featured: false,
    images: [
      "/cars/lamborghini-urus-s-2023-3.jpg",
      "/cars/lamborghini-urus-s-2023-4.jpg",
      "/cars/lamborghini-urus-s-2023-2.jpg",
      "/cars/lamborghini-urus-s-2023-1.jpg",
    ],
  },
  {
    id: "mclaren-720s-2021",
    slug: "mclaren-720s-2021",
    make: "McLaren",
    model: "720S",
    year: 2021,
    price: 320000,
    mileage: 6700,
    transmission: "7-Speed SSG",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 710,
    torque: "568 lb-ft",
    zeroToSixty: "2.8s",
    topSpeed: "212 mph",
    exteriorColor: "Papaya Spark",
    interiorColor: "Black Carbon Fibre",
    weight: "2,828 lbs",
    dimensions: "178.9\" L × 76.0\" W × 47.1\" H",
    cargo: "5.3 cu ft",
    description:
      "McLaren's most complete supercar. The 720S isn't just fast — it's intelligent. Active aerodynamics, ProActive Chassis Control II, and a carbon monocoque that weighs less than most carry-on luggage.",
    tagline: "Brilliance engineered.",
    featured: true,
    images: [
      "/cars/mclaren-720s-2021-1.jpg",
      "/cars/mclaren-720s-2021-4.jpg",
      "/cars/mclaren-720s-2021-2.jpg",
      "/cars/mclaren-720s-2021-3.jpg",
    ],
  },
  {
    id: "mclaren-artura-2023",
    slug: "mclaren-artura-2023",
    make: "McLaren",
    model: "Artura",
    year: 2023,
    price: 245000,
    mileage: 2100,
    transmission: "8-Speed DCT",
    engine: "3.0L Twin-Turbo V6 + Electric Motor",
    horsepower: 671,
    torque: "531 lb-ft",
    zeroToSixty: "3.0s",
    topSpeed: "205 mph",
    exteriorColor: "Flux Orange",
    interiorColor: "Nappa Leather Biscuit",
    weight: "3,303 lbs",
    dimensions: "174.7\" L × 74.8\" W × 47.1\" H",
    cargo: "5.3 cu ft",
    description:
      "McLaren's first series-production hybrid supercar. The Artura introduces a new twin-turbo V6 and a high-voltage electric motor, delivering instant torque and a sub-3-second sprint in complete silence — when you want it.",
    tagline: "The supercar, electrified.",
    featured: false,
    images: [
      "/cars/mclaren-artura-2023-2.jpg",
      "/cars/mclaren-artura-2023-3.jpg",
      "/cars/mclaren-artura-2023-1.jpg",
      "/cars/mclaren-artura-2023-4.jpg",
    ],
  },
  {
    id: "porsche-911-turbo-s-2023",
    slug: "porsche-911-turbo-s-2023",
    make: "Porsche",
    model: "911 Turbo S",
    year: 2023,
    price: 232000,
    mileage: 5500,
    transmission: "8-Speed PDK",
    engine: "3.8L Twin-Turbo H6",
    horsepower: 640,
    torque: "590 lb-ft",
    zeroToSixty: "2.6s",
    topSpeed: "205 mph",
    exteriorColor: "Gentian Blue Metallic",
    interiorColor: "Black/Bordeaux Red",
    weight: "3,616 lbs",
    dimensions: "178.2\" L × 74.0\" W × 51.3\" H",
    cargo: "9.9 cu ft",
    description:
      "The car against which all others are measured. Fifty years of continuous evolution produced this: a daily driver that humiliates purpose-built track machines, and does it without breaking a sweat.",
    tagline: "The benchmark. Still.",
    featured: false,
    images: [
      "/cars/porsche-911-turbo-s-2023-2.jpg",
      "/cars/porsche-911-turbo-s-2023-1.jpg",
      "/cars/porsche-911-turbo-s-2023-3.jpg",
      "/cars/porsche-911-turbo-s-2023-4.jpg",
    ],
  },
  {
    id: "porsche-taycan-turbo-s-2023",
    slug: "porsche-taycan-turbo-s-2023",
    make: "Porsche",
    model: "Taycan Turbo S",
    year: 2023,
    price: 192000,
    mileage: 8200,
    transmission: "2-Speed PDK",
    engine: "Dual Electric Motor AWD",
    horsepower: 750,
    torque: "774 lb-ft",
    zeroToSixty: "2.4s",
    topSpeed: "162 mph",
    exteriorColor: "Frozen Blue Metallic",
    interiorColor: "Black/Chalk Two-Tone",
    weight: "5,132 lbs",
    dimensions: "195.4\" L × 77.4\" W × 54.5\" H",
    cargo: "14.3 cu ft",
    description:
      "Porsche's proof that electric can be visceral. The Taycan Turbo S charges to 60 in 2.4 seconds, offers 280 miles of range, and charges at up to 270 kW. It does not apologize for any of this.",
    tagline: "Electric. Unapologetically Porsche.",
    featured: false,
    images: [
      "/cars/porsche-taycan-turbo-s-2023-1.jpg",
      "/cars/porsche-taycan-turbo-s-2023-2.jpg",
      "/cars/porsche-taycan-turbo-s-2023-3.jpg",
      "/cars/porsche-taycan-turbo-s-2023-4.jpg",
    ],
  },
  {
    id: "aston-martin-db11-2022",
    slug: "aston-martin-db11-2022",
    make: "Aston Martin",
    model: "DB11",
    year: 2022,
    price: 218000,
    mileage: 7800,
    transmission: "8-Speed Automatic",
    engine: "5.2L Twin-Turbo V12",
    horsepower: 630,
    torque: "516 lb-ft",
    zeroToSixty: "3.7s",
    topSpeed: "200 mph",
    exteriorColor: "Midnight Blue",
    interiorColor: "Cream Bridge of Weir Leather",
    weight: "3,946 lbs",
    dimensions: "186.0\" L × 76.6\" W × 50.8\" H",
    cargo: "6.6 cu ft",
    description:
      "The DB11 carries seventy years of grand touring heritage in its bones. A hand-built twin-turbo V12, a chassis tuned by the engineers who resurrected Aston Martin's reputation, and a body sculpted with obsessive attention to airflow.",
    tagline: "Seventy years of grand touring.",
    featured: false,
    images: [
      "/cars/aston-martin-db11-2022-1.jpg",
      "/cars/aston-martin-db11-2022-2.jpg",
      "/cars/aston-martin-db11-2022-3.jpg",
      "/cars/aston-martin-db11-2022-4.jpg",
    ],
  },
  {
    id: "aston-martin-vantage-2023",
    slug: "aston-martin-vantage-2023",
    make: "Aston Martin",
    model: "Vantage",
    year: 2023,
    price: 182000,
    mileage: 3300,
    transmission: "8-Speed Automatic",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 503,
    torque: "505 lb-ft",
    zeroToSixty: "3.6s",
    topSpeed: "195 mph",
    exteriorColor: "Iridescent Emerald",
    interiorColor: "Obsidian Black",
    weight: "3,593 lbs",
    dimensions: "172.6\" L × 73.5\" W × 49.5\" H",
    cargo: "9.9 cu ft",
    description:
      "Sports car purity without compromise. The Vantage is Aston Martin's most driver-focused model — a Mercedes-AMG-powered, rear-wheel-drive sports car built for those who measure weekends in corners.",
    tagline: "Raw. Purposeful. Unfiltered.",
    featured: false,
    images: [
      "/cars/aston-martin-vantage-2023-1.jpg",
      "/cars/aston-martin-vantage-2023-2.jpg",
      "/cars/aston-martin-vantage-2023-3.jpg",
      "/cars/aston-martin-vantage-2023-4.jpg",
    ],
  },
  {
    id: "bentley-continental-gt-2023",
    slug: "bentley-continental-gt-2023",
    make: "Bentley",
    model: "Continental GT",
    year: 2023,
    price: 268000,
    mileage: 4100,
    transmission: "8-Speed DSG",
    engine: "6.0L Twin-Turbo W12",
    horsepower: 626,
    torque: "664 lb-ft",
    zeroToSixty: "3.6s",
    topSpeed: "207 mph",
    exteriorColor: "Viridian",
    interiorColor: "Beluga/Linen Two-Tone",
    weight: "5,082 lbs",
    dimensions: "190.9\" L × 76.5\" W × 55.4\" H",
    cargo: "13.9 cu ft",
    description:
      "No other car reconciles extremes with such effortlessness. The Continental GT is both a 200 mph GT and a serene cruiser — hand-crafted by artisans in Crewe, England, with a W12 that makes the miles feel irrelevant.",
    tagline: "The art of effortless performance.",
    featured: false,
    images: [
      "/cars/bentley-continental-gt-2023-1.jpg",
      "/cars/bentley-continental-gt-2023-2.jpg",
      "/cars/bentley-continental-gt-2023-3.jpg",
      "/cars/bentley-continental-gt-2023-4.jpg",
    ],
  },
  {
    id: "bentley-bentayga-2022",
    slug: "bentley-bentayga-2022",
    make: "Bentley",
    model: "Bentayga",
    year: 2022,
    price: 238000,
    mileage: 9200,
    transmission: "8-Speed Automatic",
    engine: "4.0L Twin-Turbo V8",
    horsepower: 542,
    torque: "568 lb-ft",
    zeroToSixty: "4.4s",
    topSpeed: "180 mph",
    exteriorColor: "Extreme Silver",
    interiorColor: "Camel/Linen Cricket Ball Stitching",
    weight: "5,445 lbs",
    dimensions: "202.7\" L × 79.5\" W × 67.9\" H",
    cargo: "62.7 cu ft",
    description:
      "The pinnacle of the luxury SUV segment. The Bentayga offers Bentley's legendary cabin refinement — hand-stitched leather, polished veneers, and near-silence at highway speeds — with genuine off-road capability.",
    tagline: "Luxury without limits.",
    featured: false,
    images: [
      "/cars/bentley-bentayga-2022-1.jpg",
      "/cars/bentley-bentayga-2022-3.jpg",
      "/cars/bentley-bentayga-2022-4.jpg",
      "/cars/bentley-bentayga-2022-2.jpg",
    ],
  },
];

export const brands = ["Ferrari", "Lamborghini", "McLaren", "Porsche", "Aston Martin", "Bentley"];

export function getCarsByMake(make) {
  return cars.filter((c) => c.make === make);
}

export function getCarBySlug(slug) {
  return cars.find((c) => c.slug === slug) || null;
}

export function getFeaturedCars() {
  return cars.filter((c) => c.featured);
}
